### ISSUE TITLE
The toolbar only uses the portrait size on rotation

### ISSUE THREAD

**Issue by DanielMSchmidt** [rolandleth/LTHMonthYearPickerView#3]
Hi there,

Thanks for the great plugin! I just looked at my application on landscape mode and noticed, that the toolbar has only half the devise size on landscape mode. Is there refresh action on the view which I can call or is this simply a bug? 

Screenshot here:

![bildschirmfoto 2014-05-28 um 11 12 29](https://cloud.githubusercontent.com/assets/1337046/3102565/bf0a4e4c-e648-11e3-967b-a6dff909fb4b.png)

**Comment by rolandleth** [comment]
Should work properly now, with `flexibleWidth`.

**Comment by DanielMSchmidt** [comment]
Thanks, nice to know!
