### ISSUE TITLE
Cannot preselect a date in the past

### ISSUE THREAD

**Issue by boudellaredouane** [rolandleth/LTHMonthYearPickerView#7]
Hi;

I cannot preselect a date in the past using the initialDate of any of the given init methods.

After looking at the code, it seems that you are intentionally falling back to "now" `[NSDate date]` if the initial date is set in the past,

Is that required elsewhere to be the case, if not it would be great to get rid of that `if` at the beginning of the method:
`_setupComponentsFromDate`

`if ([date compare:[NSDate date]] == NSOrderedAscending) date = [NSDate date];`

**Comment by rolandleth** [comment]
Hey @boudellaredouane,

Thanks for pointing it out, I will try to have a look at it today, otherwise it'll have to wait until next week.

**Comment by rolandleth** [comment]
Fixed in d7cd670, but there are quite a few changes, and I would really appreciate it if you could lend a hand with a bit of testing. Personally, I haven't found any bugs, but more eyes are always better.

Thanks!

**Comment by boudellaredouane** [comment]
Hey @rolandleth 
I've pulled the latest commit, it's looking good.

thanks.

**Comment by rolandleth** [comment]
Hey @boudellaredouane,

Thanks for checking it out, I'll tag it and issue a CocoaPods release as well.
